ALTER TABLE __REPLACE__
  CHANGE `log_id` `log_id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  CHANGE `primary_id` `primary_id` BIGINT(20) UNSIGNED NOT NULL,
  CHANGE `member_id` `member_id` BIGINT(20) UNSIGNED NOT NULL DEFAULT '0';
